### ISSUE TITLE
Re-distribution Request

### ISSUE THREAD

**Issue by desertstsung** [cmm/gnome-user-at-host#1]
Hi, I'm having fun with [add-username-toppanel](https://github.com/brendaw/add-username-toppanel) currently, it adds user's real name as a child of battery indicator, but I also have another extension [autohide-battery](https://github.com/ai/autohide-battery) on, so the problem is that the username would disappear when my battery is fully charged.
I found that your extension adds user name as an indivitual object, I'm wondering that your better way may fix my problem.
As there is no LICENSE in your repo, I'm here to ask for redistribution right.
Thank you :)

**Comment by desertstsung** [comment]
Add new un-clickable object to either left or right side of any corner seems strange, I think I'd like goning to change the 'activities' text.
Thanks again.

**Comment by cmm** [comment]
re: redistribution: whatever is good enough for extensions.gnome.org should be good enough for anyone.

re: substance: I honestly have neither any idea about writing gnome extensions nor much of an inclination to acquire such idea; this is just an abandoned extension that I resurrected by cutting pieces off of until it did what I needed :)
